sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls

env:
  global:
    secure: U3Mqxzq44A7F1rnvVRO/MKtOHeVpYBAHid20iS0f5EDfy0x7aXUjPr4Eg6trdYBKT5fx5SDjbg7KS+xMeIjqUEXnUQsAtl0QH2pEw/B24b4Wi813tZEou/QzHf7Qf2tripHghAPBRasPtN4i54eko1pjamHjOEiIc61z/pCA0aYJvfWyTnwgNtg5PXKH8lO/xsr0KkatUAD9GeHm7U6lCCYg0TiCtzDypEYtlDZHaFC80bJK6F7kkcQCXFRrnrPHCf3nRg+/3rSqiKnZWoaidFX2gbky0ipZrDJ3hANNiBygVFuGcMKw7+WeNuYf8PsgdFhrGucCj2idh2qXDqzcKieyb4KeN9ymx8n9M2ZY99L6p/TeTDNs/i7m7yNTeNAjtHHBHKCBqS3K4TWXoiVxia7pdi6IEurNTRP/AVEpt7Hd4MDTpllp4+WGUNLX6vzo8kN4skIkMzZznWiOwxE6oT4WVmztbBbGftidv6JXo8KuKy/LK23nPC1+Nu4kT6yqjRJNrxID+06wLA/uADYjNwCFNvIHTL827QJupz55IWzlNI5uWfaiG0PnyOUEJYSu5pmvZI/0lxDbc0VWvauzdWfz7XhGFGd6ry3SktKjSXh5O4DIN68DfFc9WwjRGUDdZUgtTB5mo58oRNJzxBVMoXRh0uUqyGPvPWw6OIreySw=
