sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls

env:
  global:
    secure: te2YcmGqbhzvSZifVfBfTq2suFigyR7+JCyo/rKgUJAiank3FkXOsd5wRhYVdOBNCT2nDOGSrWf1USGwjLkdb08PLkVQhvzJNlX5pFEkByK/j6HS0267NFrmwcUM5fdYuKOEJyCoPSFgIlzZeOB5MZkul3WV9bLuMYQzjR8YE8wGGye3LVMHrQspJYyahZ/DqwtE0H1GQV/6HXGVOIqrvHtauUQbKDCEbUNJPZ4ZPZYBEbmD7Wwe3+UeBNxn7vEvVDPRGUQWYsrAeLW/gAW+NWYjie5e0GS9WodyWR6K9w7O05+B9mvlDog0PYluck7TtcsDZ4fuLCb7SbRenKWvgKw2uh6Y98JRsPgu0oL92bustDjBSUfHblo6rM2tGeuznZXm/C+6MkiHNkN2dnzjd8CH0eT9kb8gf+Q0kT8g5bbK+PVQR5jTchadYo1uMeVt0ibp49xlUYNo+aiMkFWervgjGA9HZXxO40ga9P05ac+a5x880OKZ8PZxHX4X2eWdqRBAPGuBc0uPLqv03cQ5tT6sEkULX3X60fmwM/xuPXNvu8l6qUL5VNgEID7L9DDO+ptCpSOVCzxeJGrqoXh+Lz8na8onJ8PfyaZD1BAd48y2GiZvpFwjhf2OEJgk8a1/awcRhfPur2mpot9TOZyFy9jBaj/7A47/nFyGtXiUP6Y=
